FROM centos:7

# tools for repackaging deb to rpm
RUN yum install -y epel-release
RUN yum install -y alien
RUN yum --enablerepo=epel-testing install rpmrebuild -y

# generic code builder
RUN yum install -y \
	gcc \
	gcc-c++ \
	libtool \
	libtool-ltdl \
	make \
	cmake \
       	git \
	pkgconfig \
	sudo \
	automake \
	autoconf 

# odbc build 
RUN yum install -y \
	openssl-devel \
	expat-devel \
	libpcap-devel \
	json-c-devel \
	uuid-devel \
	libuuid-devel \
	gnutls-devel \
	curl-devel \
	GeoIP-devel \
	openldap-devel \
	glib2-devel \
	libconfig-devel \
	dos2unix

RUN yum clean all

#	RUN useradd builder -u 1000 -m -G users,wheel && \
#	    echo "builder ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers && \
#	    echo "# macros"                      >  /home/builder/.rpmmacros && \
#	    echo "%_topdir    /home/builder/rpm" >> /home/builder/.rpmmacros && \
#	    echo "%_sourcedir %{_topdir}"        >> /home/builder/.rpmmacros && \
#	    echo "%_builddir  %{_topdir}"        >> /home/builder/.rpmmacros && \
#	    echo "%_specdir   %{_topdir}"        >> /home/builder/.rpmmacros && \
#	    echo "%_rpmdir    %{_topdir}"        >> /home/builder/.rpmmacros && \
#	    echo "%_srcrpmdir %{_topdir}"        >> /home/builder/.rpmmacros && \
#	    mkdir /home/builder/rpm && \
#	    chown -R builder /home/builder
#	USER builder
#	
#	ENV FLAVOR=rpmbuildtool OS=centos DIST=el7
#	CMD /srv/pkg
