FROM ubuntu:14.04

RUN apt-get update 
RUN apt-get install --assume-yes \
	build-essential \
	libboost-all-dev \
	#
	libssl-dev \
	libexpat1-dev  \
	libpcap-dev \
	libjson0 \
	libjson0-dev \
	uuid-dev \
	libuuid1 \
	libcurl4-gnutls-dev \
	libgeoip-dev \
	geoip-database \
	libldap2-dev \
	libldap-2.4-2 \
	libglib2.0-dev \
	libconfig-dev \
	dos2unix
RUN apt-get update 
